spring.application.name=techchallenge

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fiap-tech-challenge}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

jwt.secret=4bb0f3cb69f8f56f7c9b2b6efb4d0d8bceaf87f1b0efef4b6c5e0d45b9d51ab
jwt.expiration=900000

server.port=8080
